name: 'DBT_ON_CLOUD'
version: '1.0.0'
config-version: 2

# My used profile
profile: 'default'

flags:
  use_managed_iceberg: true
  use_materialization_v2: true

model-paths: ["models"]


target-path: "target"  
clean-targets:        
  - "target"
  - "dbt_packages"

models:
  DBT_ON_CLOUD:        
    silver:
      +schema: silver
      +materialized: table       
    gold:
      +schema: gold
      +materialized: table