version: 2

models:
  - name: silver_transactions
    description: "Cleaned, typed, and deduplicated transactions"
    columns:
      - name: transaction_key
        tests:
          - unique
          - not_null
      - name: invoice_id
        tests:
          - not_null
      - name: stock_code
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null
      - name: total_amount
        tests:
          - not_null
      - name: volume_category
        tests:
          - accepted_values:
                values: ['High Volume','Medium Volume','Low Volume']
      - name: price_category
        tests:
          - accepted_values:
             values: ['Premium', 'Mid Range', 'Budget']

  - name: silver_customers
    description: "Deduplicated and cleaned customer dimension"
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: country
        tests:
          - not_null
      - name: market_type
        tests:
          - accepted_values:
                values: ['Domestic', 'International']

  - name: silver_orders
    description: "Cleaned order lifecycle with delivery metrics"
    columns:
      - name: order_key
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - not_null
          - accepted_values:
              values : [ 'cancelled','delivered','in transit','pending', 'shipped']
                       
      - name: order_status_group
        tests:
          - accepted_values:
              values: ['Completed', 'In Progress',
                     'Cancelled', 'Other']